package tmux_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/noamsto/tmux-state/internal/tmux"
)

func TestParseSessions(t *testing.T) {
	input := "lazytmux\t1745700000\nwork\t1745699000\n"
	got, err := tmux.ParseSessions(input)
	if err != nil {
		t.Fatal(err)
	}
	want := []tmux.SessionRow{
		{Name: "lazytmux", LastAttached: 1745700000},
		{Name: "work", LastAttached: 1745699000},
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("ParseSessions mismatch (-want +got):\n%s", diff)
	}
}

func TestParseSessionsEmpty(t *testing.T) {
	got, err := tmux.ParseSessions("")
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Errorf("expected empty, got %d", len(got))
	}
}

func TestParseWindows(t *testing.T) {
	input := "lazytmux\t1\tmain\tabcd,200x50,0,0,1\t@4\nwork\t2\tbuild\tefgh,80x24,0,0,2\t@7\n"
	got, err := tmux.ParseWindows(input)
	if err != nil {
		t.Fatal(err)
	}
	want := []tmux.WindowRow{
		{Session: "lazytmux", Index: 1, Name: "main", Layout: "abcd,200x50,0,0,1", ID: "@4"},
		{Session: "work", Index: 2, Name: "build", Layout: "efgh,80x24,0,0,2", ID: "@7"},
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("ParseWindows mismatch (-want +got):\n%s", diff)
	}
}

func TestParsePanes(t *testing.T) {
	input := "lazytmux\t1\t1\t/home/me\tnvim\t12345\t1745700000\t%3\nlazytmux\t1\t2\t/tmp\tbash\t12346\t1745699000\t%9\n"
	got, err := tmux.ParsePanes(input)
	if err != nil {
		t.Fatal(err)
	}
	want := []tmux.PaneRow{
		{Session: "lazytmux", WindowIndex: 1, PaneIndex: 1, Cwd: "/home/me", Command: "nvim", PID: 12345, LastUsed: 1745700000, ID: "%3"},
		{Session: "lazytmux", WindowIndex: 1, PaneIndex: 2, Cwd: "/tmp", Command: "bash", PID: 12346, LastUsed: 1745699000, ID: "%9"},
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("ParsePanes mismatch (-want +got):\n%s", diff)
	}
}

func TestParseSessionsEmptyLastAttached(t *testing.T) {
	// tmux emits empty session_last_attached for sessions that have never been attached.
	got, err := tmux.ParseSessions("never-attached\t\nlazytmux\t1745700000\n")
	if err != nil {
		t.Fatalf("ParseSessions: %v", err)
	}
	want := []tmux.SessionRow{
		{Name: "never-attached", LastAttached: 0},
		{Name: "lazytmux", LastAttached: 1745700000},
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("mismatch (-want +got):\n%s", diff)
	}
}

func TestParsePanesEmptyLastUsed(t *testing.T) {
	// tmux emits empty pane_last_used for freshly-created panes.
	input := "s1\t1\t1\t/x\tbash\t1234\t\t%1\n"
	got, err := tmux.ParsePanes(input)
	if err != nil {
		t.Fatalf("ParsePanes: %v", err)
	}
	if got[0].LastUsed != 0 {
		t.Errorf("LastUsed = %d, want 0 for empty input", got[0].LastUsed)
	}
}

// TestParseWindowOptions runs against a fixture captured from real tmux
// (`tmux show-options -w`), not synthetic strings — tmux's quoting is subtle
// (empty values become two single quotes, single quotes inside a value don't
// escape, double quotes do). testdata/show-options-w.txt was generated by these five
// options on a window and dumping show-options -w; see the prefix-allowlisted
// values lazytmux actually stores (@branch / @issue_* / @pr_* titles).
func TestParseWindowOptions(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "show-options-w.txt"))
	if err != nil {
		t.Fatal(err)
	}
	got := tmux.ParseWindowOptions(string(data))
	want := map[string]string{
		"@bare":   "barevalue",
		"@spaces": "fix the thing",
		"@empty":  "",
		"@single": "a 'quoted' word",
		"@double": `a "quoted" word`,
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("ParseWindowOptions mismatch (-want +got):\n%s", diff)
	}
}

func TestParseWindowOptionsEmptyInput(t *testing.T) {
	if got := tmux.ParseWindowOptions(""); len(got) != 0 {
		t.Errorf("expected empty map, got %v", got)
	}
}
